### PR TITLE
Fix typo and grammar error

### PR DESCRIPTION
**Pull request by jaller94**
Please read the commit messages for a description of copy changes.

~~Please tag this with the label `invalid` to disqualify my minor contribution from [Hacktoberfest](https://hacktoberfest.digitalocean.com/faq). And while you're at it, tag some beginner-friendly issues with the label `hacktoberfest`. :)~~
Update: I think I changed enough to make this contribution count.

### CODE REVIEW

**Comment by GMartigny** [comment]
Why would want me to invalid your contribution? This is not much, but I'm really glad you took the time to do it.
English is not my mother's tongue, so thank you for fixing those. 
If you want more hacktober contributions, take a look at the readmes of Pencil.js, I'm sure some misspell might have slip up.

**Comment by jaller94** [comment]
Because I often contribute tiny documentation changes like this, and I don't want my Hacktoberfest PR stream to look like "fixed typo", "fixed typo", "fixed grammar error" and get disqualified from receiving the t-shirt for four merged PRs.

However, we can make the deal to not tag it `invalid` after I went through the entire documentation and ReadMe. I'll change any wording I find odd in separate commits, so you can review or interactively pick my changes on GitHub or using `git rebase --interactive HEAD` on my branch. 👍

**Comment by jaller94** [comment]
I'm done. Please review this again. :)

**Comment by GMartigny** [comment]
I'm away from home, I'll do a proper review when going back (before the end of the month 😉).

**Comment by GMartigny** [comment]
I've made some small tweak to your changes. Please tell me if these makes sense to you.

By the way, you have the best commit message I've seen in a while. I'm impressed.

**Comment by jaller94** [comment]
Looks good to me. 👍
Happy to help. I got told about this library by [bleeptrack](https://chaos.social/@bleeptrack) who uses it for several generative art projects for pen plotters including a [rocket generator for CCCamp](https://github.com/bleeptrack/cccamp19-generator).

**Comment by GMartigny** [comment]
Thanks again for you contribution !

**Pull request merged**
